[package]
name = "software_economics"
version = "0.1.0"
authors = ["QuangTung97 <quangtung29121997@gmail.com>"]
edition = "2018"

[dependencies]
assert_approx_eq = "1.1.0"
ndarray = "0.13"
ndarray-linalg = { version = "0.12", features = ["openblas"] }
